package rmtool.model.bean;
// Generated 25/04/2014 20:12:47 by Hibernate Tools 3.6.0



/**
 * Participa generated by hbm2java
 */
public class Participa  implements java.io.Serializable {


     private ParticipaId id;
     private Projeto projeto;
     private Usuario usuario;
     private int id_1;
     private Boolean funcao;

    public Participa() {
    }

	
    public Participa(ParticipaId id, Projeto projeto, Usuario usuario, int id_1) {
        this.id = id;
        this.projeto = projeto;
        this.usuario = usuario;
        this.id_1 = id_1;
    }
    public Participa(ParticipaId id, Projeto projeto, Usuario usuario, int id_1, Boolean funcao) {
       this.id = id;
       this.projeto = projeto;
       this.usuario = usuario;
       this.id_1 = id_1;
       this.funcao = funcao;
    }
   
    public ParticipaId getId() {
        return this.id;
    }
    
    public void setId(ParticipaId id) {
        this.id = id;
    }
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public Boolean getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Boolean funcao) {
        this.funcao = funcao;
    }




}


