package rmtool.model.bean;
// Generated 25/04/2014 20:12:47 by Hibernate Tools 3.6.0



/**
 * ParticipaId generated by hbm2java
 */
public class ParticipaId  implements java.io.Serializable {


     private int usuario;
     private int projeto;

    public ParticipaId() {
    }

    public ParticipaId(int usuario, int projeto) {
       this.usuario = usuario;
       this.projeto = projeto;
    }
   
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }
    public int getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(int projeto) {
        this.projeto = projeto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipaId) ) return false;
		 ParticipaId castOther = ( ParticipaId ) other; 
         
		 return (this.getUsuario()==castOther.getUsuario())
 && (this.getProjeto()==castOther.getProjeto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuario();
         result = 37 * result + this.getProjeto();
         return result;
   }   


}


