package rmtool.model.bean;
// Generated 25/04/2014 20:12:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Projeto generated by hbm2java
 */
public class Projeto  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String descricao;
     private Set participas = new HashSet(0);
     private Set requisitos = new HashSet(0);

    public Projeto() {
    }

    public Projeto(String nome, String descricao, Set participas, Set requisitos) {
       this.nome = nome;
       this.descricao = descricao;
       this.participas = participas;
       this.requisitos = requisitos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }
    public Set getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Set requisitos) {
        this.requisitos = requisitos;
    }




}


