package rmtool.model.bean;
// Generated 25/04/2014 20:12:47 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requisito generated by hbm2java
 */
public class Requisito  implements java.io.Serializable {


     private Integer id;
     private Projeto projeto;
     private Usuario usuario;
     private Requisito requisito;
     private String nome;
     private String descricao;
     private Boolean prioridade;
     private Boolean situacao;
     private String versao;
     private Boolean tipo;
     private Date criacao;
     private Set requisitos = new HashSet(0);

    public Requisito() {
    }

    public Requisito(Projeto projeto, Usuario usuario, Requisito requisito, String nome, String descricao, Boolean prioridade, Boolean situacao, String versao, Boolean tipo, Date criacao, Set requisitos) {
       this.projeto = projeto;
       this.usuario = usuario;
       this.requisito = requisito;
       this.nome = nome;
       this.descricao = descricao;
       this.prioridade = prioridade;
       this.situacao = situacao;
       this.versao = versao;
       this.tipo = tipo;
       this.criacao = criacao;
       this.requisitos = requisitos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Requisito getRequisito() {
        return this.requisito;
    }
    
    public void setRequisito(Requisito requisito) {
        this.requisito = requisito;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getPrioridade() {
        return this.prioridade;
    }
    
    public void setPrioridade(Boolean prioridade) {
        this.prioridade = prioridade;
    }
    public Boolean getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Boolean situacao) {
        this.situacao = situacao;
    }
    public String getVersao() {
        return this.versao;
    }
    
    public void setVersao(String versao) {
        this.versao = versao;
    }
    public Boolean getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Boolean tipo) {
        this.tipo = tipo;
    }
    public Date getCriacao() {
        return this.criacao;
    }
    
    public void setCriacao(Date criacao) {
        this.criacao = criacao;
    }
    public Set getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Set requisitos) {
        this.requisitos = requisitos;
    }




}


