package rmtool.model.bean;
// Generated 25/04/2014 20:12:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String login;
     private String senha;
     private String email;
     private Set participas = new HashSet(0);
     private Set requisitos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nome, String login, String senha, String email, Set participas, Set requisitos) {
       this.nome = nome;
       this.login = login;
       this.senha = senha;
       this.email = email;
       this.participas = participas;
       this.requisitos = requisitos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }
    public Set getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Set requisitos) {
        this.requisitos = requisitos;
    }




}


